### ISSUE TITLE
Using a remote MSSQL database server (scanner WI MODE)

### ISSUE THREAD

**Issue by Timpartage1** [fortify/helm3-charts#13]
hello,

I would like to use my remote MS SQL Server Dev Edition due to limitation of 10GB using SQL Express

- name: WI_SQLEXPRESS
              # Hardcoded password as it is a local datastore
              value: "Data Source=127.0.0.1;User Id=sa;Password=Str0ngP@ssw0rd?;"

https://github.com/fortify/helm3-charts/blob/main/charts/scancentral-dast/templates/scanner/scanner-statefulset.yaml

**Comment by fbordallo** [comment]
Hello,

The helm chart is prepared to use a local MSSQL Express instance. Please use the official channels to open a support ticket or an enhancement request,
In the meantime, if you know how to setup the scanner container to use an external database you can clone the repository and modify that template.

**Comment by Timpartage1** [comment]
Thank you very much for the good explanation @fbordallo 
I think we can close this issue. All the best!
