### ISSUE TITLE
Fortify license variable incorrectly set in SAST helm chart secret if not installed without --set-file argument

### ISSUE THREAD

**Issue by KyleJonas** [fortify/helm3-charts#15]
The `fortify.license` variable in `charts/scancentral-sast/templates/secret.yaml` is not being set correctly if you do not install SAST without the Helm argument `--set-file=fortifyLicense=<FORTIFY_LICENSE_PATH> .` 

`.Values.fortifyLicense` should be  `.Values.secrets.fortifyLicense` based on the format of the SAST values file.

Corrected line in the SAST [secret.yaml](https://github.com/fortify/helm3-charts/blob/1f9bcae7359a44335b38fec54efeab04d9ebda91/charts/scancentral-sast/templates/secret.yaml#L11C3-L11C18)
```
fortify.license: {{ required "fortifyLicense value is required. (Tip) Use \"helm install/upgrade\" argument --set-file=fortifyLicense=<FORTIFY_LICENSE_PATH> ." .Values.secrets.fortifyLicense | b64enc | quote }}
```

**Comment by fbordallo** [comment]
It has been corrected at [c6a236c](https://github.com/fortify/helm3-charts/commit/c6a236c30f8bebe420e1f3666c5e37dacda9b957) . Thank you for your help.
