### ISSUE TITLE
Locale Tag YAML File

### ISSUE THREAD

**Issue by michelbassan** [fortify/helm3-charts#17]
Is there anyway to set Locale settings on YAML Values File?

**Comment by fbordallo** [comment]
Sorry, I don't understand the inquiry. Can you please elaborate?

**Comment by michelbassan** [comment]
@fbordallo 
Sorry for my doubts, k8s is something new for me.

Is there any way to configure the LOCALE that the WORKER will use when downloading the rulepacks, in the values.yaml file?
By default it already downloads in EN, we have customers who use it in PT-BR

I managed to do it in a way, after deploying the Worker Pod, I entered its shell, and used the command to download the Rulepacks in PT-BR from my SSC, using the command
fortifyupdate -url <SSC-URL> -locale pt_BR -acceptSSLCertificate

**Comment by michelbassan** [comment]
In Values.yaml on worker Section, it could be something like this:

     autoUpdate:
       # Update Workers' Rulepacks before starting
       enabled: true
       server:
         # Leave empty for Fortify Update central server
         url: ""
         acceptKey: true
         acceptSslCertificate: true
         locale: pt_BR

**Comment by fbordallo** [comment]
Thank you. I understand now.
Unfortunately it isn't possible at this time, but I'll raise it as an enhancement request. Please do not hesitate to open a ticket through the official support channels requesting this feature.
We can't assist with this, but, in the meantime, If you want to have a workaround, you could look into modifying the the helm chart locally to add a modified entrypoint script to the worker container. You could do that with a configmap to replace the existing entrypoint.sh located at the container at / . You'd just need to add a line to that script to support a different locale at the section that configures fortifyupdate command.

**Comment by fbordallo** [comment]
The internal team has confirmed that an enhancement request has been created to allow to setup the locale easily using the helm chart. If you'd like to follow up, please use the official support channels and refer to this particular issue. They should be able to provide you with the enhancement request number.

I'm closing this interaction, thanks!
