### ISSUE TITLE
Worker Client SSC Secret Tokens issue

### ISSUE THREAD

**Issue by michelbassan** [fortify/helm3-charts#18]
I Have an folder with the following content
fortify.license
workertoken.txt
clientt0ken.txt
ssct0ken.txt

I Have Created a Secret:
kubectl create secret generic "scsast-secrets" --from-file "./SCSAST-Secrets"

The Secret was created successfully

On My SC-SAST Values YAML File I Have Setup Like This:

 workerAuthToken: "workertoken.txt"
 clientAuthToken: "clientt0ken.txt"
 sscScanCentralCtrlSecret: "ssct0ken.txt"

But when i deploy they cant find the key

I Have Inspected the File helm3-charts/charts/scancentral-sast/templates/controller
/controller-statefulset.yaml
At Lines 51, 56, 61

no matter what you configure in yaml it looks for these keys

key: scancentral-worker-auth-token
key: scancentral-client-auth-token
key: scancentral-ssc-scancentral-ctrl-secret

**Comment by fbordallo** [comment]
There are 2 ways to configure sensitive data in SC-SAST:
1. You can provide the sensitive tokens directly as values. In this scenario, helm will create a secret for you based on those values. You need to provide the sensitive values, not file names.
2. Create a secret in advance and provide the secret name as a Value at secrets.SecretName . In this case, you have to create a secret with the correct structure and with keys expected by SCSAST pod. If you want to do this, my suggestion is that you run the option number 1 but using `helm template`, which will show you the structure of the secret. You can copy and apply the secret later separately.

**Comment by michelbassan** [comment]
@fbordallo 

Thank you for clearing up the doubt,
I prefer to create the Secret with all the information already filled in
