### ISSUE TITLE
Repository for LIM (fortifydocker/lim) is not present in docker hub

### ISSUE THREAD

**Issue by sebrower** [fortify/helm3-charts#19]
I have tried to install the helm charts for LIM and it doesn't work because we can't pull the image from docker repo.
When I try the command **docker pull docker.io/fortifydocker/lim:23.2.ubi.8** I have the following response:

Error response from daemon: pull access denied for fortifydocker/lim, repository does not exist ... requested access to the resource is denied

I have check on docker hub and the repository for LIM is not present. How can I resolve this problem?

**Comment by fbordallo** [comment]
Hi, LIM image belongs to a private repository. Please contact support to obtain access.
