### ISSUE TITLE
Red Hat Openshfit DAST Installation Issue 

### ISSUE THREAD

**Issue by sathyatg3377** [fortify/helm3-charts#24]
Dear Team,

We are Tring to install DAST In the Red Hat Openshfit Platflorm so below i have mentioned the issue details so please check and do the needfull

Customer environment Details

- SSC 23.1 RHEL 8.9

RHEL 8.9

OpenShift Version: 4.14.8
Kustomize Version: v5.0.1
Server Version: 4.14.8
Kubernetes Version: v1.27.8+4fab27b

- Helm v3.14.0

- helm-chart version scancentral-dast-23.1.0

nginx ingress controller : not installed
default OpenShift-ingress-operator : installed
Data Base SQL Server 2019
Issue We faced in the beginning of Installation 
Value.YAML Permission Issue - Resolved
Database Connection Issue – Resolved
Network Port & IP Binding Issue – Resolved
Ingress Install Issue – Resolved
Please below Error Currently we are facing Now

CurrentError:

[root@bastion scancentral-dast]# oc logs scancentral-dast-upgrade-job-lv6jw
Defaulted container "upgrade-job" out of: upgrade-job, upgrade-prep-job (init)
2024-03-05 09:03:57 - Starting dotnet, Application Version: 23.1.0.180.
YamlDotNet.Core.YamlException: Property 'api' not found on type 'DAST.ConfigurationToolCLI.Models.Shared.ConfigurationSettingsAggregatedDTO'. (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 4, Idx: 3): Property 'api' not found on type 'DAST.ConfigurationToolCLI.Models.Shared.ConfigurationSettingsAggregatedDTO'.

![Screenshot 2024-03-06 113301](https://github.com/fortify/helm3-charts/assets/140390235/bf4b77ca-f47f-4ddd-9a6d-de233ccea72c)

![image](https://github.com/fortify/helm3-charts/assets/140390235/d4b72c20-55d4-4a96-9fd8-903214eb4236)

@fbordallo @ebell451 @akaryakina @brandon-langley-mf

**Comment by sathyatg3377** [comment]
Guy waiting for your reply

**Comment by brandon-langley-mf** [comment]
Hi @sathyatg3377 - please open this request through an official support channel.   Thanks!

**Comment by sathyatg3377** [comment]
Hi @brandon-langley-mf 

can you please share that offcical support channel details

**Comment by ebell451** [comment]
> Hi @brandon-langley-mf
> 
> can you please share that offcical support channel details

You can open a support ticket through the [Support Portal ](url)https://portal.microfocus.com/. 

Looking at the screenshot, it appears something is incorrect in your values.yaml file. Ensure the following:

- everything is escaped properly
- you haven't made any unnecessary modifications (i.e., commented out lines that shouldn't be)

**Comment by sathyatg3377** [comment]
[Troubleshooting on scancentral.pdf](https://github.com/fortify/helm3-charts/files/14575040/Troubleshooting.on.scancentral.pdf)

Hi @ebell451 & @brandon-langley-mf 
I have already raised the support but in the support they informed that need to raise issuethe github they dont know about this helm chart 

Ticket No: 02798153

and i have attached all the trobleshootoing and command line then current issue we are facing so please check and do the need

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
