### ISSUE TITLE
Missing COM_FORTIFY_SSC_ENFORCESECURETRANSPORT

### ISSUE THREAD

**Issue by PedroGarciaOT** [fortify/helm3-charts#6]
The COM_FORTIFY_SSC_ENFORCESECURETRANSPORT is missing and the option to deploy without a certificate is also missing.
My suggestion would be to check if COM_FORTIFY_SSC_ENFORCESECURETRANSPORT is true and in case it is false disable or do not configure the SSL/TLS setting in the tomcat server or in the last case as a workaround for the current image set the following required parameters to the following values.
env HTTP_SERVER_CERTIFICATE_KEYSTORE_FILE=/dev/null 
env HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD_FILE=/dev/null 
env HTTP_SERVER_CERTIFICATE_KEYSTORE_PASSWORD_FILE=/dev/null 
env HTTP_SERVER_CERTIFICATE_KEY_PASSWORD_FILE=/dev/null

**Comment by fbordallo** [comment]
The chart on this repo is the same as packaged with the official software release. Please also use the official support channels to propose changes.

It might be possible to set the env variables you are interested in. The chart allows to configure env variables with .Values.environment . Take a look at webapp.yaml. You might need to override some of the existing env variables by creating duplicate env entries at .Values.environment. It should be possible as the last duplicated env variable entry takes precedence.

Regarding COM_FORTIFY_SSC_ENFORCESECURETRANSPORT, please use the official support channels to verify if this environment variable is honored and how to configure that scenario with the Kubernetes chart.

**Comment by fbordallo** [comment]
Let's take this proposal to the SSC's PM team. Closing...
