### ISSUE TITLE
ScanCentral DAST 22.2.x - (Line: 1, Col: 1, Idx: 0): Exception during deserialization

### ISSUE THREAD

**Issue by justBeroe** [fortify/helm3-charts#8]
After installing ScanCentral DAST Chart with 'helm install scancentral-dast fortify/scancentral-dast --values fortify/dast.yaml -n fortify-dast --create-namespace' command, the following error appear:

Starting dotnet, Application Version: 22.2.0.271.
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization
---> System.Runtime.Serialization.SerializationException: Property 'debrickedSettings' not found on type 'DAST.ConfigurationToolCLI.Models.Shared.ConfigurationSettingsAggregatedDTO'.
at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)

Please provide a feedback how to resolve. Yaml attached in zip file. Thanks.

[scan-central.zip](https://github.com/fortify/helm3-charts/files/12066726/scan-central.zip)

**Comment by fbordallo** [comment]
You seem to be installing version 22.2 with 23.1 chart. Can you try helm install with `--version 22.2.1`?
23.1.0 chart includes Debricked configuration (which is being merged with your configuration) that is not recognized by 22.2 config tool.
