### ISSUE TITLE
fortifydocker/scancentral-dast-config:22.2.271.ubi.8.6 - The specified SecureBase file was not found..

### ISSUE THREAD

**Issue by justBeroe** [fortify/helm3-charts#9]
**Configuration:** [scan-central.zip](https://github.com/fortify/helm3-charts/files/12148805/scan-central.zip)

Yaml file is in zip file. 

applySecureBase: false # Allowed values: true, false

It is now failing with the error

2023-07-24 11:48:26 - Starting dotnet, Application Version: 22.2.0.271.
Validation error occured. Error code: SecureBaseFileNotFound. Error Message: The specified SecureBase file was not found..

Could you please guide here?

upgrade-job is the application that it fails at. The docker image used is fortifydocker/scancentral-dast-config:22.2.271.ubi.8.6

Thank you.

**Comment by justBeroe** [comment]
This was shared by the support team at Fortify earlier

FROM ubuntu:18.04
WORKDIR /root
COPY fortify.license /root/
COPY Fortify_SCA_and_Apps_21.2.1_linux_x64.run /root
COPY optionFile /root/
COPY S46cdba58-e45b-411c-9241-b20a1cd00980.zip /root/
RUN chmod 777 Fortify_SCA_and_Apps_21.2.1_linux_x64.run
#RUN chmod 777 optionFile
RUN pwd
#RUN zypper -n install rpm-build
RUN ./Fortify_SCA_and_Apps_21.2.1_linux_x64.run --mode unattended --optionfile /root/optionFile && rm Fortify_SCA_and_Apps_21.2.1_linux_x64.run optionFile
RUN pwd
RUN ls -la /opt/Fortify/Fortify_SCA_and_Apps_21.2.1/bin/
RUN ls -la /root/
#RUN chmod 777 sourceanalyzer fortifyupdate
RUN /opt/Fortify/Fortify_SCA_and_Apps_21.2.1/bin/fortifyupdate -import S46cdba58-e45b-411c-9241-b20a1cd00980.zip
RUN /opt/Fortify/Fortify_SCA_and_Apps_21.2.1/bin/fortifyupdate -showInstalledRules
ENTRYPOINT ["/opt/Fortify/Fortify_SCA_and_Apps_21.2.2/bin/sourceanalyzer"]
#CMD [ "/bin/bash" ]

This was related to SAST. Could you please provide a similar official dockerfile for DAST? Thank you.

**Comment by fbordallo** [comment]
Can you please open a support ticket? The config tool should not check for the SecureBase file if applySecureBase is false. It looks like it could be a defect.
